### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by petulla** [jbencook/cs171-ag-viz#2]
I just tried your visual, but the data didn't populate. Perhaps the API is down? Hoping to get to get a look.

**Comment by chornbaker** [comment]
Hi Petulla,

Thanks for the feedback. It seems to be working fine for me. The data can be slow to populate when you run the visualization from the website. It also is only currently designed to work on Chrome. These are minor issues, but I haven't had time to add a loading dialogue yet or make it compatible with other browsers.

**Comment by petulla** [comment]
yeah it i still working. nevermind!
